title: Vagabondity
description: Авторские руководства по самостоятельным путешествиям основанные на опыте
author: Дмитрий Половинкин
email: vagabondityblog.garlic252@passmail.net
url: https://vagabondity.com

#theme config
remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-feed
minima:
  skin: solarized-light
  social_links:
    - title: Vagabondity | City Walks And Atmosphere
      icon: youtube
      url: "https://www.youtube.com/@vagabondity"
    - title: Vagabondity TG Channel
      icon: telegram
      url: "https://t.me/vagabondity"

google_analytics: G-09BY2NKDYB

header_pages:
  - countries.md
  - about.md

disqus:
  shortname: vagabondity
