title: Vagabondity
description: Позитивные руководства по самостоятельному изучению мира от Дмитрия Половинкина
author:
  name: Дмитрий Половинкин
  email: vagabondityblog.garlic252@passmail.net
url: https://vagabondity.com
# theme: minima
remote_theme: jekyll/minima

header_pages:
  - about.md

#plugins:
#  - jekyll-feed
#  - jekyll-seo-tag

# Minima specific settings, which are only available from Minima 3.0 onward.
minima:
  skin: solarized-light
