title: Vagabondity
description: Позитивные руководства по самостоятельному изучению мира
author: Дмитрий Половинкин
email: vagabondityblog.garlic252@passmail.net
url: "https://vagabondity.com"

#theme config
remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme
minima:
  skin: solarized-light

header_pages:
  - posts.md
  - countries.md