title: Vagabondity
description: Позитивные руководства по самостоятельному изучению мира
author: Дмитрий Половинкин
email: vagabondityblog.garlic252@passmail.net
url: "https://vagabondity.com"

#theme config
remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme
minima:
  skin: solarized-light
  social_links:
    - title: Vagabonding Frog City Walks
      icon: youtube
      url: "https://www.youtube.com/@vagabondingfrog"

header_pages:
  - posts.md
  - countries.md
