title: Vagabondity
description: Позитивные руководства по самостоятельному изучению мира
author: Дмитрий Половинкин
email: vagabondityblog.garlic252@passmail.net
# url: https://vagabondity.com
baseurl: ""
remote_theme: jekyll/minima
minima:
  skin: dark

header_pages:
  - countries.md

plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-seo-tag
