title: Vagabondity | Самостоятельные Путешествия
description: Позитивные руководства по самостоятельным путешествиям. Создавайте свои собственные приключения!
author: Дмитрий Половинкин
email: vagabondityblog.garlic252@passmail.net
url: https://vagabondity.com

#theme config
remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-feed
minima:
  skin: solarized-light
  social_links:
    - title: Vagabonding Frog City Walks
      icon: youtube
      url: "https://www.youtube.com/@vagabondingfrog"
    - title: Vagabonding Frog - TG Channel
      icon: telegram
      url: "https://t.me/vagabondingfrog"

header_pages:
  - countries.md
  - about.md

disqus:
  shortname: vagabondity
